from PyQt6.QtWidgets import QApplication, QWidget, QPushButton, QStackedLayout
from PyQt6.QtCore import Qt, QPoint, QRect


class OctaveWidget(QWidget):   
        
    def setupUi(self, Form):    
        Form.resize(400, 300)
        self.initUI()
        
    def initUI(self):    
        
        self.C = QPushButton()
        self.C.setGeometry(QRect(0, 0, 51, 291))
        self.C.setStyleSheet("background-color:#FFFFFF")
        self.C.setText("")
        self.C.setObjectName("C")
        self.D = QPushButton()
        self.D.setGeometry(QRect(50, 0, 51, 291))
        self.D.setStyleSheet("background-color:#FFFFFF")
        self.D.setText("")
        self.D.setObjectName("D")
        self.E = QPushButton()
        self.E.setGeometry(QRect(100, 0, 51, 291))
        self.E.setStyleSheet("background-color:#FFFFFF")
        self.E.setText("")
        self.E.setObjectName("E")
        self.F = QPushButton()
        self.F.setGeometry(QRect(150, 0, 51, 291))
        self.F.setStyleSheet("background-color:#FFFFFF")
        self.F.setText("")
        self.F.setObjectName("F")
        self.G = QPushButton()
        self.G.setGeometry(QRect(200, 0, 51, 291))
        self.G.setStyleSheet("background-color:#FFFFFF")
        self.G.setText("")
        self.G.setObjectName("G")
        self.A = QPushButton()
        self.A.setGeometry(QRect(250, 0, 51, 291))
        self.A.setStyleSheet("background-color:#FFFFFF")
        self.A.setText("")
        self.A.setObjectName("A")
        self.B = QPushButton()
        self.B.setGeometry(QRect(300, 0, 51, 291))
        self.B.setStyleSheet("background-color:#FFFFFF")
        self.B.setText("")
        self.B.setObjectName("B")
        self.CSharp = QPushButton()
        self.CSharp.setGeometry(QRect(30, 0, 41, 161))
        self.CSharp.setStyleSheet("background-color:#000000")
        self.CSharp.setText("")
        self.CSharp.setObjectName("CSharp")
        self.DSharp = QPushButton()
        self.DSharp.setGeometry(QRect(80, 0, 41, 161))
        self.DSharp.setStyleSheet("background-color:#000000")
        self.DSharp.setText("")
        self.DSharp.setObjectName("DSharp")
        self.FSharp = QPushButton()
        self.FSharp.setGeometry(QRect(180, 0, 41, 161))
        self.FSharp.setStyleSheet("background-color:#000000")
        self.FSharp.setText("")
        self.FSharp.setObjectName("FSharp")
        self.GSharp = QPushButton()
        self.GSharp.setGeometry(QRect(230, 0, 41, 161))
        self.GSharp.setStyleSheet("background-color:#000000")
        self.GSharp.setText("")
        self.GSharp.setObjectName("GSharp")
        self.ASharp = QPushButton()
        self.ASharp.setGeometry(QRect(280, 0, 41, 161))
        self.ASharp.setStyleSheet("background-color:#000000")
        self.ASharp.setText("")
        self.ASharp.setObjectName("ASharp")
        
        self.resize(7 * 50, 320)
        #self.show()
